### PR TITLE
feat(trigger): allow multi-character trigger

### PR DESCRIPTION
**Pull request by mwegman**
Add the ability to pass in the trigger string to allow for more than one character.

### CODE REVIEW

**Comment by paulyoung** [comment]
This might be necessary for my needs too.

**Comment by mjrussell** [comment]
Hm I agree we should support more than one character trigger but right now the plugin is completely unaware of the trigger. That is the responsibility of the strategy function and I'd like to keep that way if possible.

What do you think about removing the prefix trim entirely and calling the onSearchChange with the entire string and letting the caller of the plugin strip whatever prefix they'd like. I could see a case where developers would like to keep the prefix also.

**Comment by paulyoung** [comment]
I was going to submit a PR today that removes [`word.substring(1, word.length)`](https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/blob/c71f07ca7f6c42976f8f5d9ddaffcbf9eed180f6/src/CompletionSuggestions/index.js#L152) and update the issues example to do that in `onIssueSearchChange` before calling the filter function.

My motivation for this is that in my case the trigger occurs at the end of a string e.g. "foo.bar." but with the current implementation, the string passed to the filter function is "oo.bar." which doesn't match anything in the suggestions list.

**Comment by mjrussell** [comment]
Closed in favor of #7

**Pull request closed without merging**
